#!/usr/bin/env php
<?php
/**
 * Console entry point do Yii2 - Dever.io
 *
 * Usado para executar migrations, seeds e outros comandos
 * via terminal/Docker.
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'dev');

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require __DIR__ . '/config/console.php';

$application = new yii\console\Application($config);
$exitCode = $application->run();
exit($exitCode);
